# .github/workflows/run-python-script.yml
name: Retrieve data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 20 9 *'  # Default cron schedule (to be updated dynamically)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script to Update Cron Schedule
        id: run_script  # Assign ID to refer to later
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python draftAPI.py  # Replace with your actual script
      - name: Commit and push JSON files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ${{ steps.run_script.outputs.folder_name }} 
          git commit -m "Add files in ${{ steps.run_script.outputs.folder_name }}"
          git push